version: '3.9'
services:
  database:
    container_name: mysql
    image: mysql:8.0.31
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: algalog
      MYSQL_ROOT_PASSWORD: algalog
